extensions:
    pim-category-edit-form:
        module: pim/category-edit-form

    pim-category-edit-form-right-panel:
        module: pim/form/common/edit-form
        parent: pim-category-edit-form
        targetZone: right-panel

    pim-category-edit-form-label:
        module: pim/category-edit-form/label
        parent: pim-category-edit-form-right-panel
        targetZone: title
        config:
            title: pim_enrich.form.category.title.edit

    pim-category-edit-form-tabs:
        module: pim/form/common/form-tabs
        parent: pim-category-edit-form-right-panel
        targetZone: content
        position: 100


#Buttons + state
    pim-category-edit-form-save-buttons:
        module: pim/form/common/save-buttons
        parent: pim-category-edit-form-right-panel
        targetZone: buttons
        position: 120

    pim-category-edit-form-save:
        module: pim/category-edit-form/save
        parent: pim-category-edit-form-right-panel
        targetZone: buttons
        position: 0

    pim-product-edit-form-delete:
        module: pim/product-edit-form/delete
        parent: pim-category-edit-form-right-panel
        targetZone: buttons
        position: 100
        config:
            trans:
                title: confirmation.remove.product
                content: pim_enrich.confirmation.delete_item
                success: pim_enrich.entity.product.info.deletion_successful
                fail: pim_enrich.entity.product.info.deletion_failed
            redirect: pim_enrich_product_index

    pim-category-edit-form-state:
        module: pim/form/common/state
        parent: pim-category-edit-form
        targetZone: state
        position: 900
        config:
            entity: pim_enrich.entity.product.title




#Tabs (history + properties)
    pim-category-edit-form-properties:
        module: pim/common/tab/properties
        parent: pim-category-edit-form-tabs
        targetZone: container
        position: 100
        config:
            label: pim_enrich.form.association_type.tab.properties.title

    pim-category-edit-form-properties-general:
        module: pim/common/properties/general
        parent: pim-category-edit-form-properties
        targetZone: accordion
        position: 100
        config:
          sectionTitle: pim_enrich.form.association_type.tab.properties.general
          codeLabel: pim_enrich.form.association_type.tab.properties.code
          formRequired: pim_enrich.form.required
          inputField: pim_enrich_association_type_form_code

    pim-category-edit-form-properties-translation:
        module: pim/common/properties/translation
        parent: pim-category-edit-form-properties
        targetZone: accordion
        position: 110
        config:
            label: pim_enrich.form.association_type.tab.properties.label_translations
            fieldBaseId: pim_enrich_association_type_form_label_

    pim-category-edit-form-history:
        module: pim/common/tab/history
        parent: pim-category-edit-form-tabs
        targetZone: container
        aclResourceId: pim_enrich_associationtype_history
        position: 120
        eventsTriggeringRendering: [pim_enrich:form:entity:post_fetch]
        config:
            class: category
            title: pim_enrich.form.association_type.tab.history.title
